version: '3'

services:
  server:
    image: darshankerudi/server1:0.2

    networks:
      - spring-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/products
      SPRING_DATASOURCE_USERNAME: darshan
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysqldb

  client:
    image: darshankerudi/rest-client:0.2
    networks:
      - spring-net
    # Add other configuration options as needed	

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products
      MYSQL_USER: darshan
      MYSQL_PASSWORD: 1234

    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
